version: "3.8"

services:
  medusa:
    build: .
    ports:
      - "9000:9000"
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgres://medusadbuser:admin717@medusadb.co9s80gqefz6.us-east-1.rds.amazonaws.com:5432/medusa-my-medusa-store?ssl=true&sslmode=require"
      REDIS_URL: "redis://ridus-cache-anzzch.serverless.use1.cache.amazonaws.com:6379"
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
